#include<iostream>
#include<exception>
using namespace std;
int main()
{
    try{
        cout<<"ENTER A NUMBER : ";
        int a;
        cin>>a;
        if(a>10 || a<0)
        {
            throw 404;
        }
    }
    catch(int x)
    {
        cout<<"ERROR "<<x<<endl;
    }

    return 0;
}
